language: r
cache: packages

addons:
  apt:
    packages:
    - libglib2.0-dev
    - libssl-dev
    - libcurl4-openssl-dev
    - libxml2-dev
    - default-jdk

before_install:
  - sudo ./inst/sh/install_cwb.sh
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_github("PolMine/polmineR.Rcpp")'

r_packages:
  - RUnit
  - devtools
  - plyr
  - tm
  - tidytext
  - rcqp
  - covr

warnings_are_errors: false

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov(token = "36cf23e7-4231-4329-b680-f052fece17dc")'
